// Bundles src/worklet/processor.ts (+ its fft.js dependency) into a single string literal
// It's then loaded as a URL Blob

import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'vite';
import type { RollupOutput } from 'rollup';

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const entry = path.join(packageRoot, 'src/worklet/processor.ts');
const outDir = path.join(packageRoot, 'src/worklet/generated');
const outFile = path.join(outDir, 'workletSource.ts');

(async () => {
  const results = (await build({
    root: packageRoot,
    configFile: false,
    logLevel: 'warn',
    build: {
      write: false,
      minify: true,
      target: 'esnext',
      lib: {
        entry,
        formats: ['iife'],
        name: 'CogsPhaseVocoderWorklet',
        fileName: () => 'processor.js',
      },
    },
  })) as RollupOutput[];

  const chunk = results[0].output.find((item) => item.type === 'chunk');
  if (!chunk) {
    throw new Error('Worklet build produced no output chunk');
  }

  await mkdir(outDir, { recursive: true });
  await writeFile(
    outFile,
    `// Generated by scripts/build-worklet.mjs from src/worklet/processor.ts. Do not edit directly.\n` +
      `export const PHASE_VOCODER_WORKLET_SOURCE = ${JSON.stringify(chunk.code)};\n`,
  );

  console.log(`Wrote worklet bundle (${chunk.code.length} chars) to ${path.relative(packageRoot, outFile)}`);
})();
