import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import { version as SDK_VERSION } from '../package.json';

const packageDir = path.resolve(fileURLToPath(import.meta.url), '../..');
const outFile = path.join(packageDir, 'src/version.ts');
const contents = `// Generated by scripts/generate-version.ts - do not edit
export const SDK_VERSION = '${SDK_VERSION}';
`;

writeFileSync(outFile, contents);
