name: 'Setup build environment'
description: 'Setup build environment'
runs:
  using: 'composite'
  steps:
    - run: corepack enable
      shell: bash
      # actions/setup-node@v6
    - uses: actions/setup-node@670825a89dc0abd596e7a3abd0f5e3f6e5faf37c
      with:
        node-version-file: '.node-version'
        cache: yarn
    - run: yarn install
      shell: bash
