name: 'Setup build environment'
description: 'Setup build environment'
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
      with:
        run_install: false
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'
        cache: pnpm
    - run: pnpm install
      shell: bash
